### ISSUE TITLE
Use JSON-LD and reuse schema.org  naming

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/map2model#19]
I noticed https://github.com/BioSchemas/Templates/blob/master/spec2model/temp_spec.json is a plain JSON but what we want is JSON-LD.

Also, "description" is referred to as "description" in schema.org. If possible it would be better to reuse schema.org naming and give new names only to new elements coming from Bioschemas.

**Comment by guicalman** [comment]
temp_spec.json was a test file, not using it any more.
