### ISSUE TITLE
Specify the specification

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/map2model#24]
I would like to be able to run the module just for the specifications I am working on. Is it possible?

Cheers,

**Comment by ljgarcia** [comment]
Looks like currently is doing just by selecting the specifications you want to commit. Will it still be possible once the commit/pull process is added to map2model?

**Comment by guicalman** [comment]
@ljgarcia, please double check [map2model readme](https://github.com/BioSchemas/map2model).

> Step 4 in [Executing map2model](https://github.com/BioSchemas/map2model#executing-map2model) and [Add new specifications](https://github.com/BioSchemas/map2model#add-new-specifications)

Hope this help ;)
