### ISSUE TITLE
Wrong path?

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/map2model#25]
Is this path "docs > specifications_md_files" correct? I run the process as described in the first part of the readme and I got the specifications on docs/spec_files. I updated that path on the execution steps but I see it is in other parts of the document as well. Not sure what is the right path.

Cheers,

**Comment by guicalman** [comment]
Yes it is correct, it doesn't matter the name of the folder, please check changes in [README.md](https://github.com/BioSchemas/map2model/README.md)
