### ISSUE TITLE
update or master branch to commit and push specs?

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/map2model#26]
After running run-py, files on the docs/spec_files folder were modified. So, in order to checkout the update branch, I have to either commit, stash or force the checkout. Is this intended?

After a stash and checkout to update branch, I got the specifications_md_files folder but there is nothing there. So, commit and pull should be done from spec_files in master?

Cheers,

**Comment by guicalman** [comment]
Documentation updated, please follow process described in [map2model README.md](https://github.com/BioSchemas/map2model/README.md)
