### ISSUE TITLE
Ignores properties that do not have a SDO description

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/map2model#29]
By 'ignore' I mean they do not appear in the finished md file despite having cardinalities and marginalities

**Comment by kcmcleod** [comment]
Though works if you have whitespace.

Note: this was noticed for profiles & types that defined new properties (so should not have a SDO description)

**Comment by kcmcleod** [comment]
Need to check if this also happens for BSC Descriptions!

**Comment by kcmcleod** [comment]
found issue in mapping.py > get_mapping_properties ()
correction fixes this, still looking for side effects

**Comment by AlasdairGray** [comment]
Will not fix
