### ISSUE TITLE
Problem with extends field in gSheets doc

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/map2model#30]
The extends ... expects the value to be from Schema.org, e.g., extends Thing

If a non schema.org value is specified, e.g., BioChemEntity, it crashes map2model and thus fails to produce a spec.

Working solution = use Thing instead of any Bioschema's type

**Comment by guicalman** [comment]
Hi Kenneth,

I just checked you have problems with extends field in the spreadsheet file.

Maybe this explanation helps you:

1. All the Bioschemas Specifications reuses or extends some properties of
schema.org
2. If a property is extended from a non schema.org vocabulary it have to be
listed as a new property.

Let me know if this short explanation helped.

Guillermo

**Comment by AlasdairGray** [comment]
Will not fix
