### ISSUE TITLE
This repository needs continuous integration

### ISSUE THREAD

**Issue by vsoch** [BioSchemas/map2model#33]
This repository needs continuous integration set up so that errored yaml isn't commit to the master branch.

**Comment by vsoch** [comment]
I want to suggest that the content in the Google Drive is moved to this (or a similar) repository so it lives directly where it's intended to be used. Google Drive is nice but not intended for use in this kind of production environment, just by way of humans being able to edit the files, and the files expected to have particular fields and formats. As an alternative, the production files should be here, tested here, and if a user wants to with with one in Google Drive there can be scripts to generate and upload / edit there, but then still bring back here to issue a pull request to contribute. I'd be glad to help make this possible if you can give me some pointers on the flow of how all these resources work together! I've been trying to simply add a containers specification and I'm lost in the wilderness at this point :P

**Comment by vsoch** [comment]
This entire picture...

![image](https://user-images.githubusercontent.com/814322/45590890-89e9c800-b8f8-11e8-8c93-620ae51be26a.png)

can be cut in half and made much simpler by focusing on clean interaction between Github and production deployment.

**Comment by AlasdairGray** [comment]
Will not fix
