### ISSUE TITLE
notes for updated repository with continuous integration

### ISSUE THREAD

**Issue by vsoch** [BioSchemas/map2model#34]
I'm working on an updated version that will simplify deployment, and want to put some notes here so I don't forget!

The following should be updated (issues directed at maintainers for each standard):

 - correct versioning should be used (e.g., 0.2.0 and not 0.2 or v0.2, etc.)
 - the configuration.yml should have an assigned maintainer (or maintainers)
 - for each folder with multiple "Mapping (1)... Mapping (2)" assign issue to figure out why there are copies, designate correct file.

The following should just be tested in continuous integration:

 - folders in specifications that have missing or improperly formatted / specified content
 - version strings are correct
 - all yaml is correctly formatted
 - preview of site content as artifact
 - on merge (or hold -> approve), deploy?

And possibly with a bot could be deployed after PR passes instead of needing second Pull Request, but I don't know enough about the process to determine this.

Going to proceed work here https://github.com/vsoch/map2model/tree/remove-gdrive No ETA with timing  because, well Florence! swoooosh! :tornado:  Super excited about this!

**Comment by vsoch** [comment]
Some additional things to think about:

 - to what extent do we need to represent ALL modules (specs) to be rendered if a user is only updating / adding one?
 - what about instead providing a docker container (e.g., an openbase) to handle this entire thing?

**Comment by vsoch** [comment]
- run.py (entrypoint for container) should have argument parser proper, with reasonable defaults.

**Comment by AlasdairGray** [comment]
Will not fix
